import { prisma } from "../src/database/prisma"

const unidadesEscolares = [
  "CAIC ELOMIR SILVA", "CASA DA CRIANCA DE INOÃ", "CASA DA CRIANÇA DE ITAIPUAÇU",
  "CEIM DÓ RÉ MI HAROLDO SANT ANNA SANTINI", "CEIM MARILZA DA CONCEIÇÃO ROCHA MEDINA",
  "CEIM NELSON MANDELA", "CEIM PINGUINHOS DE LUZ", "CEIM PROFESSOR JOSÉ CARLOS DE ALMEIDA E SILVA",
  "CEIM PROFESSORA LUCIANA PEIXOTO DE OLIVEIRA VIANNA", "CEIM PROFESSORA ONDINA DE OLIVEIRA COELHO",
  "CEIM RECANTO DA AMIZADE", "CEIM SIDNÉIA DA SILVA COSTA", "CEIM VALÉRIA RAMOS PASSOS",
  "CEM JOANA BENEDICTA RANGEL", "CEPT PROFESSORA ZILCA LOPES DA FONTOURA",
  "CRECHE MUNICIPAL ESTRELINHAS DO AMANHÃ", "E M ESPRAIADO", "E M GUARATIBA",
  "E M PROF ATALIBA DE MACEDO DOMINGUES", "EM ADEMILDA MUNIZ SIMÕES", "EM ALCEBÍADES AFONSO VIANA FILHO",
  "EM ALFREDO NICOLAU DA SILVA JUNIOR", "EM AMANDA PENA DE AZEVEDO SOARES", "EM AMAURY GOMES DO NASCIMENTO",
  "EM ANÍSIO SPÍNOLA TEIXEIRA", "EM ANTONIO LOPES DA FONTOURA", "EM ANTONIO RUFINO DE SOUZA FILHO",
  "EM BARRA DE ZACARIAS", "EM BENVINDO TAQUES HORTA", "EM BRASILINA COUTINHO",
  "EM CARLOS MAGNO LEGENTIL DE MATTOS", "EM CARLOS MANOEL COSTA LIMA", "EM CLÉRIO BOECHAT DE OLIVEIRA",
  "EM CONEGO BATALHA", "EM DA MATA ATLÂNTICA", "EM DE APLICAÇÃO JOSÉ PEREIRA DA SILVA",
  "EM DE IDOSOS MILTON FELIPE DINIZ", "EM DE INOÃ", "EM DIRCE MARINHO GOMES",
  "EM INDIGENA GUARANI KYRINGUE ARANDUA", "EM INDIGENA GUARANI PARA POTI NHE E JA",
  "EM JACINTHO LUIZ CAETANO", "EM JOÃO MONTEIRO", "EM JOÃO PEDRO MACHADO",
  "EM JOAQUIM EUGENIO DOS SANTOS", "EM LÊDA MARIA DO AMPARO LEMOS", "EM LUCIMERE RODRIGUES DE MELO",
  "EM LUCIO THOMÉ GUERRA FETEIRA", "EM MARCUS VINICIUS CAETANO SANTANA", "EM MARIA CRISTINA DE LIMA CORRÊA",
  "EM MARISA LETÍCIA LULA DA SILVA", "EM MARQUES DE MARICÁ", "EM MAURÍCIO ANTUNES DE CARVALHO",
  "EM MINISTRO LUIS SPARANO", "EM PAULO FREIRE", "EM PINDOBAS", "EM PROFESORA ALCIONE SOARES RANGEL DA SILVA",
  "EM PROFESSOR DARCY RIBEIRO", "EM PROFESSOR OSWALDO LIMA RODRIGUES", "EM PROFESSORA DILZA DA SILVA SA REGO",
  "EM PROFESSORA MARÍLIA SOUSA DA SILVA NUNES", "EM PROFESSORA ROMILDA DOS SANTOS",
  "EM REGINALDO DOMINGUES DOS SANTOS", "EM RETIRO", "EM RITA SAMPAIO CARTAXO",
  "EM ROMILDA NUNES LINDA", "EM SÃO BENTO DA LAGOA", "EM VEREADOR ANICETO ELIAS",
  "EM VEREADOR JOÃO DA SILVA BEZERRA", "EM VEREADOR LEVY CARLOS RIBEIRO",
  "EM VEREADOR OSDEVALDO MARINS DA MATTA", "EM WILSON SARDINHA DA SILVA",
  "JIM PROFESSORA ENILZEA SABINO DA COSTA PIRES", "JIM PROF BARBARA RODRIGUES DA SILVA",
  "JIM PROFESSOR RICARDO COUTO DE AGUIAR", "JIM PROFESSORA MARA REJANE GOMES BUENO",
  "JIM PROFESSORA MARIA DE LOURDES CRUZ SILVA", "JIM PROFESSORA MARIA HONORINA ZANINI BERNARDO",
  "JIM PROFESSORA SABRINA SANTIAGO HENRIQUES", "JIM RYNALDA RODRIGUES DA SILVA",
  "JIM TRENZINHO DA ESPERANÇA", "SECRETARIA DE EDUCAÇÃO", "CIEC - JOÃO VINÍCIUS FERREIRA SIMÕES",
  "CIEC - IVANISA DO NASCIMENTO SILVA", "JIM CONSUELO TARQUÍNIO DUQUE (PEQUENOS NAVEGANTES)",
  "CIEM COMANDANTE LUCIANO MORETTI LOPES"
]

async function main() {
  console.log('Iniciando seed das unidades escolares...')

  for (const nome of unidadesEscolares) {
    await prisma.escola.upsert({
      where: { nome: nome },
      update: {},
      create: {
        nome: nome,
      },
    })
  }

  console.log('Seed finalizado com sucesso!')
}

main()
  .catch((e) => {
    console.error(e)
    process.exit(1)
  })
  .finally(async () => {
    await prisma.$disconnect()
  })